### ISSUE TITLE
A question about the matrix_init function

### ISSUE THREAD

**Issue by myst729** [parastuffs/mesange_keyboard#2]
In [config.h](https://github.com/parastuffs/mesange_keyboard/blob/main/9-keys-74hc595/firmware/9keysSR/config.h#L17-L20) you defined row pins as:
```c
/* row pins */
#define ROW_A  C6
#define ROW_B  D7
#define ROW_C  E6
```

But in [matrix.c](https://github.com/parastuffs/mesange_keyboard/blob/main/9-keys-74hc595/firmware/9keysSR/matrix.c#L61-L72), the `matrix_init` function set pin input for rows as:
```c
/**
 * Row pins PD2, PD3... PD7 are input for rows A-F.
 * The rows are pulled low with a pull-down resistor.
 *
 * The columns are scanned using two 74hc595 in series on pins defined in config.h.
 */
void matrix_init(void) {
    setPinInput(D5); /* Arduino denomination */
    setPinInput(D6);
    setPinInput(D7);
```

I couldn't figure out the relation between the row pins and the pin input being set. Also the comment for the function is confusing. Could you share some insight?

**Comment by parastuffs** [comment]
Hi, sorry for the delay.
In the [Pro Micro pinout details](https://github.com/parastuffs/mesange_keyboard/blob/main/datasheets/ProMicro16MHzv1.pdf), there are two denominations:
- "Ports" which are used in `config.h`  (`C6`, `D7`, with the `P` omitted).
- "Arduino" for `matrix.c` (`D5`, `D6`, ...)

**Comment by myst729** [comment]
I didn't notice the bootloader is caterina. So they're the light green labels in the picture you posted, I get it. But it's weird.

If I'm using an on board chip (a bare 32u4 MCU or others from AVR), then the code would be:
```
void matrix_init(void) {
    setPinInput(C6);
    setPinInput(D7);
    setPinInput(E6);
```
this same as in config.h, right?

**Comment by parastuffs** [comment]
I would guess so ¯\\_(ツ)_/¯ Never tried a bare 32u4 myself.
